
function [val] = Lsfc_h_natasha(phi, th, t)
%% Derived by Natasha in Mathematica
%
val = sech((3.*cos(th).*sin(phi - (3.*sqrt(3).*sec(th).*sech(3.*cos(th)).^2.*tanh(3.*cos(th)))/2))/5).^2.*tan(th).*...
    ((-3.*sin(th).*sin(phi - (3.*sqrt(3).*sec(th).*sech(3.*cos(th)).^2.*tanh(3.*cos(th)))/2))/5 + ...
    (3.*cos(th).*cos(phi - (3.*sqrt(3).*sec(th).*sech(3.*cos(th)).^2.*tanh(3.*cos(th)))/2).*...
    ((9.*sqrt(3).*sech(3.*cos(th)).^4.*tan(th))/2 - (3.*sqrt(3).*sec(th).*sech(3.*cos(th)).^2.*tan(th).*tanh(3.*cos(th)))/2 -...
    9.*sqrt(3).*sech(3.*cos(th)).^2.*tan(th).*tanh(3.*cos(th)).^2))/5) -...
    sech((3.*cos(th).*sin(phi - (3.*sqrt(3).*sec(th).*sech(3.*cos(th)).^2.*tanh(3.*cos(th)))/2.))/5).^2.*...
    ((-3.*cos(th).*sin(phi - (3.*sqrt(3).*sec(th).*sech(3.*cos(th)).^2.*tanh(3.*cos(th)))/2.))/5 - ...
    (6.*cos(phi - (3.*sqrt(3).*sec(th).*sech(3.*cos(th)).^2.*tanh(3.*cos(th)))/2.).*sin(th).*...
    ((9.*sqrt(3).*sech(3.*cos(th)).^4.*tan(th))/2 - (3.*sqrt(3).*sec(th).*sech(3.*cos(th)).^2.*tan(th).*tanh(3.*cos(th)))/2 - ...
    9.*sqrt(3).*sech(3.*cos(th)).^2.*tan(th).*tanh(3.*cos(th)).^2))/5 - ...
    (3.*cos(th).*sin(phi - (3.*sqrt(3).*sec(th).*sech(3.*cos(th)).^2.*tanh(3.*cos(th)))/2).*...
    ((9.*sqrt(3).*sech(3.*cos(th)).^4.*tan(th))/2 - (3.*sqrt(3).*sec(th).*sech(3.*cos(th)).^2.*tan(th).*tanh(3.*cos(th)))/2 - ...
    9.*sqrt(3).*sech(3.*cos(th)).^2.*tan(th).*tanh(3.*cos(th)).^2).^2)/5 + ...
    (3.*cos(th).*cos(phi - (3.*sqrt(3).*sec(th).*sech(3.*cos(th)).^2.*tanh(3.*cos(th)))/2).*...
    ((9.*sqrt(3).*sec(th).^2.*sech(3.*cos(th)).^4)/2 + (9.*sqrt(3).*sech(3.*cos(th)).^4.*tan(th).^2)/2 - ...
    (3.*sqrt(3).*sec(th).^3.*sech(3.*cos(th)).^2.*tanh(3.*cos(th)))/2 + 108.*sqrt(3).*sech(3.*cos(th)).^4.*sin(th).*tan(th).*tanh(3.*cos(th)) - ...
    (3.*sqrt(3).*sec(th).*sech(3.*cos(th)).^2.*tan(th).^2.*tanh(3.*cos(th)))/2 - 9.*sqrt(3).*sec(th).^2.*sech(3.*cos(th)).^2.*tanh(3.*cos(th)).^2 -...
    9.*sqrt(3).*sech(3.*cos(th)).^2.*tan(th).^2.*tanh(3.*cos(th)).^2 - 54.*sqrt(3).*sech(3.*cos(th)).^2.*sin(th).*tan(th).*tanh(3.*cos(th)).^3))/5) +...
    2.*sech((3.*cos(th).*sin(phi - (3.*sqrt(3).*sec(th).*sech(3.*cos(th)).^2.*tanh(3.*cos(th)))/2.))/5.).^2.*...
    ((-3.*sin(th).*sin(phi - (3.*sqrt(3).*sec(th).*sech(3.*cos(th)).^2.*tanh(3.*cos(th)))/2.))/5 + ...
    (3.*cos(th).*cos(phi - (3.*sqrt(3).*sec(th).*sech(3.*cos(th)).^2.*tanh(3.*cos(th)))/2).*...
    ((9.*sqrt(3).*sech(3.*cos(th)).^4.*tan(th))/2 - (3.*sqrt(3).*sec(th).*sech(3.*cos(th)).^2.*tan(th).*tanh(3.*cos(th)))/2 - ...
    9.*sqrt(3).*sech(3.*cos(th)).^2.*tan(th).*tanh(3.*cos(th)).^2))/5).^2.*...
    tanh((3.*cos(th).*sin(phi - (3.*sqrt(3).*sec(th).*sech(3.*cos(th)).^2.*tanh(3.*cos(th)))/2))/5) + ...
    sec(th).^2.*((3.*cos(th).*sech((3.*cos(th).*sin(phi - (3.*sqrt(3).*sec(th).*sech(3.*cos(th)).^2.*tanh(3.*cos(th)))/2))/5).^2.*...
    sin(phi - (3.*sqrt(3).*sec(th).*sech(3.*cos(th)).^2.*tanh(3.*cos(th)))/2))/5 + ...
    (18.*cos(th).^2 .*cos(phi - (3.*sqrt(3).*sec(th).*sech(3.*cos(th)).^2.*tanh(3.*cos(th)))/2).^2.*...
    sech((3.*cos(th).*sin(phi - (3.*sqrt(3).*sec(th).*sech(3.*cos(th)).^2.*tanh(3.*cos(th)))/2))/5).^2.*...
    tanh((3.*cos(th).*sin(phi - (3.*sqrt(3).*sec(th).*sech(3.*cos(th)).^2.*tanh(3.*cos(th)))/2))/5))/25);
end