
function [val] = Lsfc_h_evan(phi, th, t)
%% DERIVED BY EVAN IN MATHEMATICA:
%
val = csc(phi).^2.*((3.*cos(phi).*sech((3.*cos(phi).*sin(th - (sqrt(3).*t.*sec(phi).*sech(3.*cos(phi)).^2.*tanh(3.*cos(phi)))/2))/5).^2.*sin(th - (sqrt(3).*t.*sec(phi).*sech(3.*cos(phi)).^2.*tanh(3.*cos(phi)))/2))/5 + ...
    (18.*cos(phi).^2.*cos(th - (sqrt(3).*t.*sec(phi).*sech(3.*cos(phi)).^2.*tanh(3.*cos(phi)))/2.0).^2.*sech((3.*cos(phi).*sin(th - (sqrt(3).*t.*sec(phi).*sech(3.*cos(phi)).^2.*tanh(3.*cos(phi)))/2.0))/5.0).^2.* ...
    tanh((3.*cos(phi).*sin(th - (sqrt(3).*t.*sec(phi).*sech(3.*cos(phi)).^2.*tanh(3.*cos(phi)))/2.0))/5.0))/25.0) + ...
    csc(phi).*(-(cos(phi).*sech((3.*cos(phi).*sin(th - (sqrt(3).*t.*sec(phi).*sech(3.*cos(phi)).^2.*tanh(3.*cos(phi)))/2.0))/5.0).^2.* ...
    ((-3.*sin(phi).*sin(th - (sqrt(3).*t.*sec(phi).*sech(3.*cos(phi)).^2.*tanh(3.*cos(phi)))/2.0))/5.0 + ...
    (3.*cos(phi).*cos(th - (sqrt(3).*t.*sec(phi).*sech(3.*cos(phi)).^2.*tanh(3.*cos(phi)))/2.0).* ...
    ((3.*sqrt(3).*t.*sech(3.*cos(phi)).^4.*tan(phi))/2.0 - (sqrt(3).*t.*sec(phi).*sech(3.*cos(phi)).^2.*tan(phi).*tanh(3.*cos(phi)))/2.0 - 3.*sqrt(3).*t.*sech(3.*cos(phi)).^2.*tan(phi).*tanh(3.*cos(phi)).^2))/5.0)) - ...
    sech((3.*cos(phi).*sin(th - (sqrt(3).*t.*sec(phi).*sech(3.*cos(phi)).^2.*tanh(3.*cos(phi)))/2.0))/5.0).^2.*sin(phi).* ...
    ((-3.*cos(phi).*sin(th - (sqrt(3).*t.*sec(phi).*sech(3.*cos(phi)).^2.*tanh(3.*cos(phi)))/2.0))/5.0 - ...
    (6.*cos(th - (sqrt(3).*t.*sec(phi).*sech(3.*cos(phi)).^2.*tanh(3.*cos(phi)))/2.0).*sin(phi).* ...
    ((3.*sqrt(3).*t.*sech(3.*cos(phi)).^4.*tan(phi))/2.0 - (sqrt(3).*t.*sec(phi).*sech(3.*cos(phi)).^2.*tan(phi).*tanh(3.*cos(phi)))/2.0 - 3.*sqrt(3).*t.*sech(3.*cos(phi)).^2.*tan(phi).*tanh(3.*cos(phi)).^2))/5.0 - ...
    (3.*cos(phi).*sin(th - (sqrt(3).*t.*sec(phi).*sech(3.*cos(phi)).^2.*tanh(3.*cos(phi)))/2.0).* ...
    ((3.*sqrt(3).*t.*sech(3.*cos(phi)).^4.*tan(phi))/2.0 - (sqrt(3).*t.*sec(phi).*sech(3.*cos(phi)).^2.*tan(phi).*tanh(3.*cos(phi)))/2.0 - 3.*sqrt(3).*t.*sech(3.*cos(phi)).^2.*tan(phi).*tanh(3.*cos(phi)).^2).^2)/5.0 + ...
    (3.*cos(phi).*cos(th - (sqrt(3).*t.*sec(phi).*sech(3.*cos(phi)).^2.*tanh(3.*cos(phi)))/2.0).* ...
    ((3.*sqrt(3).*t.*sec(phi).^2.*sech(3.*cos(phi)).^4)/2.0 + (3.*sqrt(3).*t.*sech(3.*cos(phi)).^4.*tan(phi).^2)/2.0 - (sqrt(3).*t.*sec(phi).^3.*sech(3.*cos(phi)).^2.*tanh(3.*cos(phi)))/2.0 + ...
    36.*sqrt(3).*t.*sech(3.*cos(phi)).^4.*sin(phi).*tan(phi).*tanh(3.*cos(phi)) - (sqrt(3).*t.*sec(phi).*sech(3.*cos(phi)).^2.*tan(phi).^2.*tanh(3.*cos(phi)))/2.0 - 3.*sqrt(3).*t.*sec(phi).^2.*sech(3.*cos(phi)).^2.*tanh(3.*cos(phi)).^2 - ...
    3.*sqrt(3).*t.*sech(3.*cos(phi)).^2.*tan(phi).^2.*tanh(3.*cos(phi)).^2 - 18.*sqrt(3).*t.*sech(3.*cos(phi)).^2.*sin(phi).*tan(phi).*tanh(3.*cos(phi)).^3))/5.0) + ...
    2.*sech((3.*cos(phi).*sin(th - (sqrt(3).*t.*sec(phi).*sech(3.*cos(phi)).^2.*tanh(3.*cos(phi)))/2.0))/5.0).^2.*sin(phi).* ...
    ((-3.*sin(phi).*sin(th - (sqrt(3).*t.*sec(phi).*sech(3.*cos(phi)).^2.*tanh(3.*cos(phi)))/2.0))/5.0 + ...
    (3.*cos(phi).*cos(th - (sqrt(3).*t.*sec(phi).*sech(3.*cos(phi)).^2.*tanh(3.*cos(phi)))/2.0).* ...
    ((3.*sqrt(3).*t.*sech(3.*cos(phi)).^4.*tan(phi))/2.0 - (sqrt(3).*t.*sec(phi).*sech(3.*cos(phi)).^2.*tan(phi).*tanh(3.*cos(phi)))/2.0 - 3.*sqrt(3).*t.*sech(3.*cos(phi)).^2.*tan(phi).*tanh(3.*cos(phi)).^2))/5.0).^2.*...
    tanh((3.*cos(phi).*sin(th - (sqrt(3).*t.*sec(phi).*sech(3.*cos(phi)).^2.*tanh(3.*cos(phi)))/2.0))/5.0)) ;
end